services:
  - type: web
    name: devtinder-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dtjfafddc
      - key: CLOUDINARY_UPLOAD_PRESET
        value: devtinder_unsigned
